import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Arkapal',
      email: 'arkapal280719das@gmail.com',
      password: bcrypt.hashSync('123abc'),
      isAdmin: true,
    },
    {
      name: 'Arka',
      email: 'arkadas@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'High quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'Levis Men T-Shirt',
      slug: 'Levis-Men-T-Shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 8,
      countInStock: 5,
      brand: 'Levis',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      name: 'U.S. POLO ASSN. Mens Regular T-Shirt',
      slug: 'U.S.-POLO-ASSN.-Mens-Regular-T-Shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 10,
      countInStock: 15,
      brand: 'US Polo',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ],
};
export default data;
